name: registro_personas_indocumentadas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  image_picker: ^1.1.0
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.0
  intl: ^0.19.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#003366"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/agente.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  
